# https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
name: "deploy-that"
description: "Deploy that project to github pages"

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: globe
  color: purple

inputs:
  language:
    description: "Which language is the project"
    required: true
    default: "javascript"
  directory:
    description: "Directory to work"
    required: true
    default: "."
  output_directory:
    description: "Output directory"
    required: true
    default: "dist"
  checkout_submodules:
    description: "Should checkout with submodules"
    required: true
    default: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: ${{ inputs.checkout_submodules }}
    - name: Add node
      if: ${{ inputs.language == 'javascript' }}
      uses: actions/setup-node@v4
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Run deployer.sh
      run: bash $GITHUB_ACTION_PATH/deployer.sh
      shell: bash
      env:
        LANGUAGE: ${{ inputs.language }}
        DIRECTORY: ${{ inputs.directory }}
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.output_directory }}
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    - name: Finish
      shell: bash
      run: echo "Finished deployment at $URL"
      env:
        URL: ${{ steps.deployment.outputs.page_url }}
