# Simple workflow for deploying static content to GitHub Pages
name: Update latest tag

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

permissions:
    contents: write

jobs:
    # Single deploy job since we're just deploying
    tag:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - name: Create tag
              uses: actions/github-script@v5
              with:
                  script: |
                      github.rest.git.createRef({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        ref: 'refs/tags/latest',
                        sha: context.sha
                      }).catch(err => {
                        if (err.status !== 422) throw err;
                        github.rest.git.updateRef({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            ref: 'tags/latest',
                            sha: context.sha
                        });
                      });
